name: planner
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  sqflite: ^2.2.0+2
  sqflite_common_ffi_web:
  path: ^1.8.2
  shared_preferences: ^2.0.15
  provider: ^6.0.0
  flutter_date_pickers: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true